
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.ServerSocket;
import java.net.Socket;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * client_.java
 *
 * Created on Nov 2, 2019, 2:00:49 PM
 */

/**
 *
 * @author class-12
 */
public class client_ extends javax.swing.JFrame {
static DataInputStream din;
static DataOutputStream dout;
static Socket s;
static ServerSocket ss;static int i=1200,w=1;
static String id="b",id2="a";
    /** Creates new form client_ */
    public client_() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("client1");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTextField1.setText("jTextField1");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String msg=jTextField1.getText();
            jTextArea1.append("you: "+msg+"\n");
            dout=new DataOutputStream(s.getOutputStream());
            dout.writeUTF(msg);
        } catch(Exception e){
            System.out.println(e);
        }
        // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
  
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new client_().setVisible(true);
            }
        });System.out.println("okay");
        try {s = new Socket("127.0.0.1",1200);
        din=new DataInputStream(s.getInputStream());
        dout=new DataOutputStream(s.getOutputStream());
        String msgin="";
        System.out.println("okay2");
        while(!msgin.equals("exit")){msgin=din.readUTF();
               jTextArea1.append(id2+": "+msgin+"\n");
             
            }}
        catch(Exception e){
            System.out.println(e);
            if(e.toString().equals("java.net.ConnectException: Connection refused: connect")){
              String msgin="" ;
              try{
           ss=new ServerSocket(i);
           s=ss.accept();
           System.out.println("server on");
           din=new DataInputStream(s.getInputStream());
           dout=new DataOutputStream(s.getOutputStream());
           while(true){
               msgin=din.readUTF();
               jTextArea1.append(id2+": "+msgin+"\n");
               if(msgin.equals("exit")){
                   ss.close();
               }
                
           }

       }
       catch(Exception o){System.out.print(o+"pp");
        }
          }
else if(e.toString().equals("java.net.SocketException: Connection reset")){
              String msgin="" ;
       try{
           ss=new ServerSocket(1200);
           s=ss.accept();
System.out.println("server on");
           din=new DataInputStream(s.getInputStream());
           dout=new DataOutputStream(s.getOutputStream());

           while(true){
               msgin=din.readUTF();

               jTextArea1.append(id2+": "+msgin+"\n");
                if(msgin.equals("exit")){
                   s.close();
               } 
      
           }

       }
       catch(Exception o){System.out.print(o +"ll");
        }
          }
          else{System.out.println(e+"kk");}}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
