/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * request.java
 *
 * Created on Aug 22, 2019, 12:17:19 PM
 */

package message;

import java.sql.*;
import javax.swing.DefaultListModel;

/**
 *
 * @author class-12
 */
public class request extends javax.swing.JFrame {
String u_name;
    /** Creates new form request */
    public request() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jButton1)
                .addContainerGap(327, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    try{    String Query;String name;
     Connection con = message.getConnection();
     Statement s=con.createStatement();
     ResultSet r =s.executeQuery("select * from "+u_name+"_req;");
     Statement s1=con.createStatement();
     ResultSet r1 ;
     DefaultListModel a=new DefaultListModel();int count =0;
     while(r.next()){
         ++count;
         System.out.println("3");
     }
     r =s.executeQuery("select * from "+u_name+"_req;");
     rp[] c=new rp[count];int i=0;
     while(r.next()){
       rp m=new rp();
       name=r.getString(1);
       try{
       r1=s1.executeQuery("select * from "+name+";");
       if(r1.next()){}
       rp.my=u_name;
       m.setVisible(true);

       rp.name=r.getString(1);
       System.out.println(rp.name);
       rp.my=u_name;
       jList1.add(m);
       }
       catch(Exception ex){
           System.out.println(ex);
           Query="delete from "+u_name+"_req where requests='"+name+"';";
    s1.executeUpdate(Query);

         }
       
     }
    }
    catch(Exception e){System.out.println(e);}// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        try{
            Connection con = message.getConnection();
            Statement s=con.createStatement();
            ResultSet r =s.executeQuery("select * from "+u_name+"_req;");
            DefaultListModel a=new DefaultListModel();int count =0;
            while(r.next()){
             ++count;

             }
     r.first();
     rp[] c=new rp[count];int i=0;
     while(r.next()){
       rp m=new rp();
       rp.name=r.getString(1);
       rp.my=u_name;
       c[i]=m;

     }
    }
    catch(Exception e){System.out.println(e);}      // TODO add your handling code here:
    }//GEN-LAST:event_jList1ValueChanged

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
my_profile a=new my_profile();
a.u_name=u_name;
a.setVisible(true);
this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new request().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
