     /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * update_profile.java
 *
 * Created on Sep 25, 2019, 3:50:16 PM
 */

package message;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author class-12
 */
public class update_profile extends javax.swing.JFrame {
File sm;String u_name,iid,uname;
boolean password=false,user=false,image=false,about_me=false,email=false;
    /** Creates new form update_profile */
    public update_profile() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPasswordField4 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "profile pic", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton2.setText("update profile pic");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("your id");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jLabel3.setText("re-type your new password");
        jLabel3.setOpaque(true);

        jLabel2.setText("type your new password");
        jLabel2.setOpaque(true);

        jLabel4.setText("your user name");

        jLabel5.setText("about me");

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextArea1CaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusLost(evt);
            }
        });
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyPressed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPasswordField3.setNextFocusableComponent(jPasswordField1);
        jPasswordField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField3ActionPerformed(evt);
            }
        });
        jPasswordField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField3FocusLost(evt);
            }
        });

        jLabel7.setText("type your password");
        jLabel7.setOpaque(true);

        jButton3.setText("update your id");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("update your user name");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("update your password");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("update your info");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel8.setText("type your password");
        jLabel8.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(jPasswordField4, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(jPasswordField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton2)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton3))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButton4))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jPasswordField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                    .addContainerGap())))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addContainerGap()))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   try{     jFileChooser1.showOpenDialog(null);
        sm=jFileChooser1.getSelectedFile();
        if(sm==null){image=false;}
        String Path=sm.getAbsolutePath();
        ImageIcon a=new ImageIcon(new ImageIcon(Path).getImage().getScaledInstance(100, 98, Image.SCALE_SMOOTH));

        jLabel6.setIcon(a);
        if(image){image=false;jButton2.setName("update image");}
  else{image=true;jButton2.setName("do not update image");}}
   catch(Exception ex){}// TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

}//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/messenger?zeroDateTimeBehavior=convertToNull", "root", "root");
            Statement s=con.createStatement();
            String id,uid;
            id=jTextField1.getText();
            id=id.trim();
            ResultSet r=s.executeQuery("select id from id where id =\""+id+"\";");
            if(r.next()){uid=r.getString(1);
                if(uid.equals(u_name)){
                 jButton1.setEnabled(true);
                }
                else{int a=JOptionPane.showConfirmDialog(null, "id is already in use\n use another id?", "error", 0, 0);
                if(a==0){jTextField1.setText("");}
            jButton1.setEnabled(false);}} else if(id.equals("")){JOptionPane.showMessageDialog(null, "id cannot be empty", "error", 0);
            jButton1.setEnabled(false);} else{jButton1.setEnabled(true);}// TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(sign_up.class.getName()).log(Level.SEVERE, null, ex);
        }    // TODO add your handling code here:
}//GEN-LAST:event_jTextField1FocusLost

    private void jTextArea1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextArea1CaretUpdate
        // TODO add your handling code here:
}//GEN-LAST:event_jTextArea1CaretUpdate

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
     // TODO add your handling code here:
}//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
       // TODO add your handling code here:
}//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jPasswordField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusLost
        String pass,re_pass,uname;
        pass=new String(jPasswordField1.getPassword());
        uname=jTextField2.getText();
        re_pass=new String(jPasswordField2.getPassword());
        if(!pass.equals(re_pass)){JOptionPane.showMessageDialog(null, "password not matching re type password", "error", 0);
        jButton1.setEnabled(false);}
        else if(pass.trim().equals("")){JOptionPane.showMessageDialog(null, "password must only contain A-Z or a-z or 0-9 or @ or . \n not anyother special character or spaces or be empty", "error", 0);
        jButton1.setEnabled(false);}
        else{jButton1.setEnabled(true);}    // TODO add your handling code here:
}//GEN-LAST:event_jPasswordField2FocusLost

    private void jPasswordField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyPressed
        // TODO add your handling code here:
}//GEN-LAST:event_jPasswordField2KeyPressed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
uname=jTextField1.getText();        // TODO add your handling code here:
}//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/messenger?zeroDateTimeBehavior=convertToNull", "root", "root");
            Statement s=con.createStatement();
            String id,uid;
            id=jTextField2.getText();
            id=id.trim();
            ResultSet r=s.executeQuery("select u_name from id where u_name =\""+id+"\";");
            if(r.next()){uid=r.getString(1);
                if(uid.equals(u_name)){
                 jButton1.setEnabled(true);
                }
                else{JOptionPane.showMessageDialog(null, "user name is already taken", "error", 0);
            jButton1.setEnabled(false);}} else if(id.equals("")){JOptionPane.showMessageDialog(null, "user name cannot be empty", "error", 0);
            jButton1.setEnabled(false);} else{jButton1.setEnabled(true);}// TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(sign_up.class.getName()).log(Level.SEVERE, null, ex);
        }   // TODO add your handling code here:
}//GEN-LAST:event_jTextField2FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{
         Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/messenger?zeroDateTimeBehavior=convertToNull", "root", "root");
            Statement s=con.createStatement();
    Statement s1=con.createStatement();
    uname=jTextField2.getText();
    String pass=new String(jPasswordField4.getPassword());
      ResultSet r=s.executeQuery("select * from id where id ='"+iid+"';");

      if(r.next()){
          if(r.getString("password").equals(pass)){



          }
          else{JOptionPane.showMessageDialog(null, "wrong password", "error", 0);}
      }
    System.out.println(uname);
    if(image){
        PreparedStatement st=con.prepareStatement("update "+u_name+"_profile set img=?;");
            FileInputStream t=new FileInputStream(sm);
            st.setBinaryStream(1, (InputStream)t, (int)sm.length());
            st.execute();
    }
    if(email){
        String id=jTextField1.getText();
        s.executeUpdate("update id set id='"+id+"' where id='"+iid+"';");
    }
    if(user){
        s.executeUpdate("update id set u_name='"+uname+"' where u_name='"+u_name+"';");
         r=s.executeQuery("select * from "+u_name+";");
        while(r.next()){
        String friend,type;
        friend=r.getString(1);
        type=r.getString(2);
        s1.executeUpdate("update "+friend+" set member_of='"+uname+"' where member_of='"+u_name+"';");
        if(type.equals("friend")){
        try{
        s1.executeUpdate("alter table msg_"+u_name+"_"+friend+" rename msg_"+uname+"_"+friend+";");
        s1.executeUpdate("alter table msg_"+uname+"_"+friend+" change "+u_name+" "+uname+" varchar(40) default 'unread'");
        s1.executeUpdate("update msg_"+uname+"_"+friend+" set id='"+uname+"' where id='"+u_name+"';");
        }
        catch(Exception ex){
            System.out.println(ex);
            s1.executeUpdate("alter table msg_"+friend+"_"+u_name+" rename msg_"+friend+"_"+uname+";");
            s1.executeUpdate("alter table msg_"+friend+"_"+uname+" change "+u_name+" "+uname+" varchar(40) default 'unread';");
            s1.executeUpdate("update msg_"+friend+"_"+uname+" set id='"+uname+"' where id='"+u_name+"';");
        }}
        else{s1.executeUpdate("update "+friend+"_req set requests='"+uname+"' where requests='"+u_name+"';");}
        s1.executeUpdate("alter table "+u_name+" rename "+uname+";");
        s1.executeUpdate("alter table "+u_name+"_profile rename "+uname+"_profile;");
        s1.executeUpdate("alter table "+u_name+"_req rename "+uname+"_req;");
        }
    }
    if(about_me){
        String id=jTextArea1.getText();
        s.executeUpdate("update "+uname+"_profile set about_me ='"+id+"' where id='"+uname+"';");
    }
    if(password){
       pass=new String(jPasswordField1.getPassword());System.out.println("update id set password='"+pass+"' where u_name='"+uname+"';");
      String q="update id set password='"+pass+"' where u_name='"+uname+"';";
    s1.executeUpdate(q);
   }
    my_profile a=new my_profile();
    a.u_name=uname;
    a.setVisible(true);
    this.dispose();
}
catch(Exception e){
System.out.println(e);
} 

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
try{String id,about,pass;byte[] img;
    Connection con =message.getConnection();
    Statement s=con.createStatement();
    ResultSet r=s.executeQuery("select * from id where u_name=\""+u_name+"\";");
    if(r.next()){

        id=r.getString("id");
        uname=r.getString("u_name");
        jTextField1.setText(id);
        jTextField2.setText(uname);
        pass=r.getString("password");
        
iid=id;
    }
    r=s.executeQuery("select * from "+u_name+"_profile;");
    if(r.next()){
        about=r.getString("about_me");
        img=r.getBytes("img");
        ImageIcon image = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(150, 120, Image.SCALE_SMOOTH));
            jLabel6.setIcon(image);jTextArea1.append(about);
    }
}
catch(Exception e){System.out.println(e);}// TODO add your handling code here:
jPasswordField1.setVisible(false);
jPasswordField2.setVisible(false);
jPasswordField3.setVisible(false);
jLabel2.setVisible(false);
jLabel3.setVisible(false);
jLabel7.setVisible(false);
jTextField1.setEnabled(false);
jTextField2.setEnabled(false);
jTextArea1.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 jPasswordField3.setVisible(true);
 jLabel7.setVisible(true);
  if(password){password=false;jPasswordField3.setVisible(false);jButton5.setName("update password");
  jLabel7.setVisible(false);}
  else{password=true;jButton5.setName("do not update password");
 }       // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jPasswordField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField3ActionPerformed
  try {
        Class.forName("com.mysql.jdbc.Driver");
   Connection      con=DriverManager.getConnection("jdbc:mysql://localhost:3306/messenger?zeroDateTimeBehavior=convertToNull", "root", "root");
      Statement   s=con.createStatement();
      String pass;
      pass=new String(jPasswordField3.getPassword());
      ResultSet r=s.executeQuery("select * from id where id ='"+iid+"';");
      if(r.next()){
          if(r.getString("password").equals(pass)){
              jPasswordField2.setVisible(true);
jPasswordField1.setVisible(true);
jPasswordField1.setText("");
jPasswordField2.setText("");
jLabel2.setVisible(true);
jLabel3.setVisible(true);
if(password==false){password=true;}
else{password=false;
jPasswordField2.setVisible(false);
jPasswordField1.setVisible(false);
jPasswordField1.setText("");
jPasswordField2.setText("");
jLabel2.setVisible(false);
jLabel3.setVisible(false);}
}
          else{JOptionPane.showMessageDialog(null, "wrong password", "error", 0);}
      }

    } catch (Exception ex) {
        System.out.println(ex);
    }       // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField3ActionPerformed

    private void jPasswordField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField3FocusLost
try {
        Class.forName("com.mysql.jdbc.Driver");
   Connection      con=DriverManager.getConnection("jdbc:mysql://localhost:3306/messenger?zeroDateTimeBehavior=convertToNull", "root", "root");
      Statement   s=con.createStatement();
      String pass;
      pass=new String(jPasswordField3.getPassword());
      ResultSet r=s.executeQuery("select * from id where id ='"+iid+"';");
      if(r.next()){
          if(r.getString("password").equals(pass)){
              jPasswordField2.setVisible(true);
jPasswordField1.setVisible(true);
jPasswordField1.setText("");
jPasswordField2.setText("");
jLabel2.setVisible(true);
jLabel3.setVisible(true);
if(password==false){password=true;}
else{password=false;
jPasswordField2.setVisible(false);
jPasswordField1.setVisible(false);
jPasswordField1.setText("");
jPasswordField2.setText("");
jLabel2.setVisible(false);
jLabel3.setVisible(false);}
}
          else{JOptionPane.showMessageDialog(null, "wrong password", "error", 0);}
      }

    } catch (Exception ex) {
        System.out.println(ex);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField3FocusLost

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 jTextArea1.setEnabled(true);
  if(about_me){about_me=false;jTextField1.setEnabled(false);jButton6.setName("update info");}
  else{about_me=true;jButton6.setName("do not update info");}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  jTextField1.setEnabled(true);
  if(email){email=false;jTextField1.setEnabled(false);jButton3.setName("update id");}
  else{email=true;jButton3.setName("do not update id");}// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 jTextField2.setEnabled(true);
  if(user){user=false;jTextField2.setEnabled(false);jButton4.setName("update user name");}
  else{user=true;jButton4.setName("do not update user name");}       // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
